import Link from "next/link";
import Button from "@/components/Button";

export default function TermsPage() {
  return (
    <div className="flex flex-1 flex-col">
      <header className="h-16 border-b border-border">
        <nav className="mx-auto flex h-full w-full max-w-[1200px] items-center justify-between px-4 sm:px-6">
          <Link href="/" className="flex items-center gap-2 text-base font-bold text-foreground">
            <span
              aria-hidden="true"
              className="flex h-6 w-6 items-center justify-center rounded-[6px] bg-primary text-white"
            >
              <svg
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="3"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M5 12l14 0" />
                <path d="M13 6l6 6-6 6" />
              </svg>
            </span>
            NextStep
          </Link>
          <Button href="/start" variant="primary" size="sm">
            Start Exploring
          </Button>
        </nav>
      </header>

      <main className="mx-auto w-full max-w-[720px] flex-1 px-4 py-14 sm:px-6">
        <h1 className="text-3xl font-bold text-foreground">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted">Last updated: 4 September 2026</p>

        <div className="mt-8 space-y-8 text-base leading-7 text-foreground">
          <section>
            <h2 className="text-xl font-semibold text-foreground">
              1. Acceptance of Terms
            </h2>
            <p className="mt-2 text-muted">
              By using NextStep, you agree to these Terms of Service. If you do
              not agree, please do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              2. The Service
            </h2>
            <p className="mt-2 text-muted">
              NextStep is a web application that helps you clarify your goals
              and find a next step based on what you share. The service uses AI
              to understand your input and suggest goals and action plans.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              3. Your Use of the Service
            </h2>
            <p className="mt-2 text-muted">
              You are responsible for the information you provide. You agree
              not to misuse the service or use it for any unlawful purpose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              4. AI Suggestions
            </h2>
            <p className="mt-2 text-muted">
              Suggestions, goals, and action plans generated by NextStep are
              provided to support your thinking. They are not professional
              advice. You remain responsible for the decisions you make.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              5. Limitation of Liability
            </h2>
            <p className="mt-2 text-muted">
              To the fullest extent permitted by law, NextStep is not liable
              for any indirect or consequential damages arising from your use
              of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              6. Changes to These Terms
            </h2>
            <p className="mt-2 text-muted">
              We may update these Terms from time to time. Continued use of the
              service after changes means you accept the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              7. Contact
            </h2>
            <p className="mt-2 text-muted">
              If you have questions about these Terms, you can reach us through
              the contact information provided in the Privacy Policy.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
